AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-async-invocation
Transform:
- AWS::Serverless-2016-10-31

Resources:
  demoS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: renan-demo2
  
  demoSQSStandardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: renan-demo-queue

  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Events: s3:ObjectCreated:*
            Bucket: 
              Ref: demoS3Bucket
  
  helloSQSLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-from-queue.helloFromLambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      MemorySize: 128
      Description: A Lambda function that returns a static string.
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt demoSQSStandardQueue.Arn

Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
