AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a private and public repository

Resources:
  DemoPrivateRepository:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration: 
        ScanOnPush: true
      RepositoryName: demo-private-repository
      LifecyclePolicy:
        LifecyclePolicyText: |
          { "rules": [{
              "rulePriority": 1,
              "description": "Expires older prod images",
              "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["prod"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 1
              },
              "action": {
                  "type": "expire"
              }
            }
          ]}        